#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: devsecops-stack setup — DefectDojo + Semgrep (SAST) + OWASP ZAP (DAST)
# ──────────────────────────────────────────────────────────────────────────

cd "$(dirname "${BASH_SOURCE[0]}")"
ENV_FILE=".env"
TOTAL_STAGES=8

# ── helpers local to this wizard ──────────────────────────────────────────
_rand() { openssl rand -base64 $(( $1 * 2 )) | tr -d '\n/+=' | cut -c1-"$1"; }   # _rand LEN: exactly LEN [A-Za-z0-9]
# _project: compose's normalised project name for this directory (or COMPOSE_PROJECT_NAME).
_project() {
  if [[ -n "${COMPOSE_PROJECT_NAME:-}" ]]; then printf '%s' "$COMPOSE_PROJECT_NAME"; return; fi
  basename "$PWD" | tr '[:upper:]' '[:lower:]' | sed -e 's/[^a-z0-9_-]//g' -e 's/^[^a-z0-9]*//'
}
_tls_on() { [[ "$(_existing COMPOSE_FILE || true)" == *compose.tls.yaml* && -n "$(_existing DD_DOMAIN || true)" ]]; }
_dd_url() {
  if _tls_on; then printf 'https://%s' "$(_existing DD_DOMAIN)"
  else printf 'http://localhost:%s' "$(_existing DD_PORT || echo 8080)"; fi
}
_run_scan() {                       # _run_scan <import-service>
  printf '\n  %s$ docker compose --profile scan run --rm %s%s\n\n' "$DIM" "$1" "$RESET"
  local rc
  set +e
  docker compose --profile scan run --rm "$1" 2>&1 \
    | grep -vE ' (Pulling|Pulled|Extracting|Downloading|Verifying|Waiting|Healthy|Exited|Creating|Created|Starting|Started|Running) ?'
  rc=${PIPESTATUS[0]}
  set -e
  if [[ "$rc" -eq 0 ]]; then
    printf '  %s✓ %s finished%s\n' "$GREEN" "$1" "$RESET"
  else
    warn "$1 failed — see output above (reports are in ./reports/)"
    SKIPPED+=("scan $1 failed; re-run: docker compose --profile scan run --rm $1")
  fi
}

banner "devsecops-stack setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Prerequisites"
say "Checking Docker, Compose v2 and the .env file."
if ! command -v docker >/dev/null 2>&1; then
  warn "docker is not installed. Install Docker Engine + Compose plugin, then re-run."
  open_url "https://docs.docker.com/engine/install/"
  exit 1
fi
if ! docker compose version >/dev/null 2>&1; then
  warn "'docker compose' (v2 plugin) not found. Install docker-compose-plugin, then re-run."
  exit 1
fi
printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$(docker --version)"
printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$(docker compose version)"

if ! docker info >/dev/null 2>&1; then
  warn "The Docker daemon is not running."
  if command -v systemctl >/dev/null 2>&1 && confirm "Start it now with 'sudo systemctl start docker'?"; then
    sudo systemctl start docker
    sleep 2
    docker info >/dev/null 2>&1 || { warn "still can't reach the daemon; start it manually and re-run"; exit 1; }
    printf '  %s✓ docker daemon started%s\n' "$GREEN" "$RESET"
  else
    warn "Start the daemon (e.g. 'sudo systemctl start docker' or open Docker Desktop) and re-run."
    exit 1
  fi
else
  printf '  %s✓%s docker daemon is running\n' "$GREEN" "$RESET"
fi

if [[ ! -f "$ENV_FILE" ]]; then
  cp .env.example "$ENV_FILE"
  printf '  %s✓ created%s %s from .env.example (defaults for DB, versions, etc.)\n' "$GREEN" "$RESET" "$ENV_FILE"
else
  note "$ENV_FILE exists — existing values are offered as defaults; Enter keeps them."
fi
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "DefectDojo admin & secrets"
say "These credentials log you into the dashboard; the import step also uses them"
say "to fetch an API token, so they must be set before the first 'compose up'."
printf '\n'
ask DD_ADMIN_USER "Admin username:"
DD_ADMIN_USER="${DD_ADMIN_USER:-admin}"
write_env DD_ADMIN_USER "$DD_ADMIN_USER"

DB_INITIALISED=""
if docker volume ls -q 2>/dev/null | grep -qx "$(_project)_defectdojo_postgres"; then
  DB_INITIALISED=1
  warn "DefectDojo's database already exists: the admin password was fixed on first boot."
  warn "Keep the current value (Enter). To change it, do so in the DefectDojo UI, or wipe"
  warn "everything with 'docker compose --profile scan down -v' and re-run this wizard."
else
  note "Leave the password empty to generate a random one (shown in the summary)."
fi
ask_secret DD_ADMIN_PASSWORD "Admin password:"
if [[ -z "$DB_INITIALISED" && ( -z "$DD_ADMIN_PASSWORD" || "$DD_ADMIN_PASSWORD" == "change-me-please" ) ]]; then
  DD_ADMIN_PASSWORD=$(_rand 20)
  GENERATED_PASSWORD=1
  note "generated a random admin password"
fi
write_env DD_ADMIN_PASSWORD "$DD_ADMIN_PASSWORD"

ask DD_PORT "Dashboard port:"
DD_PORT="${DD_PORT:-8080}"
write_env DD_PORT "$DD_PORT"

for key in DD_SECRET_KEY:64 DD_CREDENTIAL_AES_256_KEY:32; do
  name="${key%%:*}"; len="${key#*:}"
  cur=$(_existing "$name" || true)
  if [[ -z "$cur" || "$cur" == change-me-* ]]; then
    write_env "$name" "$(_rand "$len")"
    note "generated $name ($len chars)"
  else
    note "$name already set — keeping it (changing it would break stored credentials)"
  fi
done
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "HTTPS (Let's Encrypt, optional)"
say "nginx can serve DefectDojo on https:// with a free Let's Encrypt certificate."
say "Needs a public DNS name pointing at this host, with ports 80 and 443 open to the"
say "internet. Skip for local use (http://localhost:$(_existing DD_PORT || echo 8080))."
printf '\n'
if _tls_on; then note "HTTPS is enabled for $(_existing DD_DOMAIN)."; fi
if confirm "Serve DefectDojo over HTTPS with Let's Encrypt?"; then
  ask DD_DOMAIN "Public DNS name (e.g. defectdojo.example.com):"
  while [[ ! "$DD_DOMAIN" =~ ^[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?(\.[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?)+$ ]]; do
    ask DD_DOMAIN "Enter a fully qualified domain name:"
  done
  write_env DD_DOMAIN "$DD_DOMAIN"
  ask LETSENCRYPT_EMAIL "Contact email for Let's Encrypt (optional):"
  write_env LETSENCRYPT_EMAIL "${LETSENCRYPT_EMAIL:-}"
  write_env COMPOSE_FILE "compose.yaml:compose.tls.yaml"
  write_env DD_ALLOWED_HOSTS "$DD_DOMAIN,127.0.0.1"

  resolved=$(getent ahostsv4 "$DD_DOMAIN" 2>/dev/null | awk 'NR==1{print $1}' || true)
  if [[ -z "$resolved" ]]; then
    warn "$DD_DOMAIN does not resolve yet; certbot keeps retrying every 30 min until it does."
  else
    note "$DD_DOMAIN resolves to $resolved; that address must reach this host on ports 80/443."
  fi
  if docker info --format '{{.SecurityOptions}}' 2>/dev/null | grep -q rootless \
     && (( $(sysctl -n net.ipv4.ip_unprivileged_port_start 2>/dev/null || echo 1024) > 80 )); then
    warn "Rootless Docker can't bind ports 80/443 yet. Allow it with:"
    note "    echo 'net.ipv4.ip_unprivileged_port_start=80' | sudo tee /etc/sysctl.d/99-rootless-ports.conf"
    note "    sudo sysctl --system && systemctl --user restart docker"
    SKIPPED+=("allow rootless Docker to bind ports 80/443 (see RUNNING-AS-USER.md)")
  fi
else
  if _tls_on; then
    note "keeping HTTPS as configured. To turn it off, remove COMPOSE_FILE from $ENV_FILE."
  else
    note "skipped. DefectDojo stays on plain HTTP."
  fi
fi
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "SAST target (Semgrep)"
say "Semgrep scans a source tree on this machine and files findings under a"
say "DefectDojo *product*. Use one product per application."
printf '\n'
ask DD_PRODUCT_NAME "Product name in DefectDojo (e.g. my-app):"
while [[ -z "$DD_PRODUCT_NAME" || "$DD_PRODUCT_NAME" == "my-app" ]]; do
  ask DD_PRODUCT_NAME "Product name is required — enter one:"
done
write_env DD_PRODUCT_NAME "$DD_PRODUCT_NAME"

note "Absolute path of the repository to scan (mounted read-only into the container)."
ask SCAN_PATH "Source path:"
SCAN_PATH="${SCAN_PATH/#\~/$HOME}"
while [[ ! -d "$SCAN_PATH" ]]; do
  warn "'$SCAN_PATH' is not a directory."
  ask SCAN_PATH "Source path:"
  SCAN_PATH="${SCAN_PATH/#\~/$HOME}"
done
SCAN_PATH=$(cd "$SCAN_PATH" && pwd)
write_env SCAN_PATH "$SCAN_PATH"

note "Rule set: p/default (balanced), p/security-audit (noisier), p/owasp-top-ten,"
note "auto (language-detected, needs network), or a path to your own rules."
ask SEMGREP_CONFIG "Semgrep config:"
write_env SEMGREP_CONFIG "${SEMGREP_CONFIG:-p/default}"
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "DAST target (OWASP ZAP)"
say "ZAP needs a *running* web app to crawl. The URL is resolved from inside the"
say "ZAP container, so 'localhost' will NOT work. Use one of:"
step "app in another container: attach it to the network"
note "    docker network connect devsecops-stack_default <container>"
note "    then ZAP_TARGET=http://<container>:<port>"
step "app on this host: ZAP_TARGET=http://host.docker.internal:<port>"
note "    (Linux: add  extra_hosts: [\"host.docker.internal:host-gateway\"]  to the zap"
note "     services in compose.yaml — see README)"
step "app anywhere else: its public URL, e.g. https://staging.example.com"
printf '\n'
ask ZAP_TARGET "Target URL:"
while [[ -z "$ZAP_TARGET" || "$ZAP_TARGET" == "http://example.com" || "$ZAP_TARGET" =~ ^https?://localhost ]]; do
  warn "Enter a real URL reachable from a container (not localhost)."
  ask ZAP_TARGET "Target URL:"
done
write_env ZAP_TARGET "$ZAP_TARGET"

note "Optional flags passed to zap-baseline / zap-full-scan, e.g. '-j' (AJAX spider),"
note "'-m 10' (max spider minutes). Leave empty for none."
ask ZAP_EXTRA_ARGS "Extra ZAP args:"
write_env ZAP_EXTRA_ARGS "${ZAP_EXTRA_ARGS:-}"
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Start DefectDojo"
say "Runs 'docker compose up -d'. First boot pulls ~2 GB of images and runs"
say "database migrations; allow 1–3 minutes."
printf '\n'
if confirm "Start (or update) the DefectDojo stack now?"; then
  docker compose up -d
  printf '\n  %swaiting for the dashboard to become healthy%s' "$DIM" "$RESET"
  for _ in $(seq 1 60); do
    if [[ "$(docker compose ps nginx --format '{{.Health}}' 2>/dev/null)" == "healthy" ]]; then break; fi
    printf '.'; sleep 5
  done
  printf '\n'
  if [[ "$(docker compose ps nginx --format '{{.Health}}' 2>/dev/null)" == "healthy" ]]; then
    printf '  %s✓ DefectDojo is up at %s%s\n' "$GREEN" "$(_dd_url)" "$RESET"
    if _tls_on; then
      note "Until Let's Encrypt issues the certificate (~1 min), the browser warns about a"
      note "self-signed placeholder. Watch progress with: docker compose logs -f certbot"
    fi
    step "Log in with user '$DD_ADMIN_USER' and the admin password."
    open_url "$(_dd_url)/login"
  else
    warn "nginx is not healthy yet. Check: docker compose logs -f uwsgi nginx"
    SKIPPED+=("DefectDojo did not report healthy — check 'docker compose logs'")
  fi
else
  note "skipped — start later with: docker compose up -d"
  SKIPPED+=("start DefectDojo: docker compose up -d")
fi
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Run scans"
say "Each scan runs its scanner, then pushes the report into DefectDojo"
say "(product '$DD_PRODUCT_NAME'). Reports are also saved to ./reports/."
printf '\n'
step "1) Semgrep SAST        — $SCAN_PATH"
step "2) ZAP baseline DAST   — passive crawl of $ZAP_TARGET (safe)"
step "3) ZAP full DAST       — ACTIVE attack scan of $ZAP_TARGET (slow, intrusive)"
step "a) all of the above     n) none"
printf '\n'
printf '  %sWhich scans? (e.g. 1 2, or a) [1 2]:%s ' "$BOLD" "$RESET"
read -r choice || true
choice="${choice:-1 2}"
[[ "$choice" == a ]] && choice="1 2 3"

if [[ "$choice" != n ]]; then
  if ! docker info >/dev/null 2>&1 || [[ "$(docker compose ps nginx --format '{{.Health}}' 2>/dev/null)" != "healthy" ]]; then
    warn "DefectDojo is not running/healthy; scans need it for the import step."
    SKIPPED+=("run scans once DefectDojo is up (see summary for commands)")
  else
    for c in $choice; do
      case "$c" in
        1) _run_scan import-semgrep ;;
        2) _run_scan import-zap ;;
        3)
          warn "The full scan sends real attack payloads to $ZAP_TARGET."
          if confirm "You own / are authorised to attack this target — proceed?"; then
            _run_scan import-zap-full
          else
            note "skipped ZAP full scan"
          fi ;;
        *) warn "unknown choice '$c' — skipped" ;;
      esac
    done
  fi
else
  note "no scans run"
fi
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Summary"
finish
say "Dashboard:   $(_dd_url)   (user: $DD_ADMIN_USER)"
if [[ -n "${GENERATED_PASSWORD:-}" ]]; then
  say "Password:    $DD_ADMIN_PASSWORD   ${DIM}(generated — also stored in .env)${RESET}"
fi
printf '\n'
say "Run scans again any time:"
note "  docker compose --profile scan run --rm import-semgrep"
note "  docker compose --profile scan run --rm import-zap"
note "  docker compose --profile scan run --rm import-zap-full"
say "Scan a different repo/app without editing .env:"
note "  SCAN_PATH=/other/repo DD_PRODUCT_NAME=other docker compose --profile scan run --rm import-semgrep"
say "Stop everything:   docker compose --profile scan down"
printf '\n'
